version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: my-redis-project
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: >
      redis-server --requirepass strongpassword123
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
# Use strong secured password in production