spring.application.name=pts-scheduler-service

spring.jpa.open-in-view=false

spring.datasource.url=jdbc:postgresql://localhost:5432/ptsDb
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver
# Keep the connection alive if idle for a long time (needed in production)
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1
# Show or not log for each sql query
spring.jpa.show-sql=true
# Force table creation from entity definitions
spring.jpa.hibernate.ddl-auto=none

# Allows Hibernate to generate SQL optimized for a particular DBMS
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.mhridin.pts_common.kafka
app.kafka.topics.price-check=price-check-tasks

app.scheduling.interval-ms=3600000
